### ISSUE TITLE
Error encountered when pasting image into existing card

### ISSUE THREAD

**Issue by beepboopbeep3000** [BlueGreenMagick/image-style-editor#11]
Anki called out this addon. However, the error persisted after I disabled the addon. I had to also disable ImageResizer to eliminate the error.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.38 (355e4cd5) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-21 08:59:59

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 35, in cmd
  File "aqt\webview.py", line 124, in _onCmd
  File "aqt\webview.py", line 569, in _onBridgeCmd
  File "<decorator-gen-116>", line 2, in onBridgeCmd
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
  File "C:\Users\david\AppData\Roaming\Anki2\addons21\1593969147\__init__.py", line 573, in onBridgeCmd
    return _old(self, cmd)
  File "aqt\editor.py", line 442, in onBridgeCmd
  File "aqt\editor.py", line 944, in onPaste
  File "aqt\editor.py", line 1062, in onPaste
  File "aqt\editor.py", line 1056, in _onPaste
  File "<decorator-gen-14>", line 2, in _processMime
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
TypeError: _processMime_around() got multiple values for argument '_old'

**Comment by BlueGreenMagick** [comment]
I don't think the problem is with this add-on, but I think another add-on monkey patched `Editor.onPaste` function incorrectly. 

Sorry for the late reply!
