### ISSUE TITLE
Not working on 2.1.30

### ISSUE THREAD

**Issue by HarryLang100** [BlueGreenMagick/image-style-editor#8]
Hello. This add-on is not working for me at all. My Anki version is 2.1.30. When I click OK on the Style Editor dialog box, I get the following error message. This happens even if I disable all other add-ons.

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.30 (06a69c25) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-18 23:26:52

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-12>", line 2, in onBridgeCmd
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\harry\AppData\Roaming\Anki2\addons21\1593969147\__init__.py", line 551, in onBridgeCmd
    main.modify_fields(cmd)
  File "C:\Users\harry\AppData\Roaming\Anki2\addons21\1593969147\__init__.py", line 501, in modify_fields
    editor.note.flush()
  File "anki\notes.py", line 67, in flush
AssertionError

**Comment by BlueGreenMagick** [comment]
Same issue as #9 - Fixed!
