### ISSUE TITLE
Error message when used while creating cards

### ISSUE THREAD

**Issue by PaulKnauseder** [BlueGreenMagick/image-style-editor#9]
Hello

I am using version 3.1.33 and when I try to resize an image while in the "add cards window" I get an error message. 

------------------------------------------------
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-06 19:29:28

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-84>", line 2, in onBridgeCmd
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\Paul\AppData\Roaming\Anki2\addons21\1593969147\__init__.py", line 551, in onBridgeCmd
    main.modify_fields(cmd)
  File "C:\Users\Paul\AppData\Roaming\Anki2\addons21\1593969147\__init__.py", line 501, in modify_fields
    editor.note.flush()
  File "anki\notes.py", line 67, in flush
AssertionError
------------------------------------------------

**Comment by BlueGreenMagick** [comment]
Thanks for the detail, Fixed!

**Comment by sroka-m** [comment]
Hello! similar problem. I just wanted to resize image that is too big with image occlusion and i got this. Then I disabled all add-ons but this one and the same error appeared. I am not desperate for the fix, but i am just reporting, maybe you  will find it felpful. Have a good day. 
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-12-21 14:51:54

err#TypeError: Cannot read property 'complete' of null
